### ISSUE TITLE
Missing 'positional' argument in current code

### ISSUE THREAD

**Issue by sihyun-yu** [mtensor/rulesynthesis#1]
Hi, first of all, thank you for your nice research and for providing the code.
I tried to reproduce the result based on uploaded code, but it seems there's no 'args.positional' argument in synthTrain.py, while model.py requires this argument to create the model.

Could you please check it or tell me how can I solve this issue?

**Comment by mtensor** [comment]
Thanks, I added the arg to synthTrain.py, it should run now. Let me know if you still have problems.
